logging:
  logLevel: INFO

config:
  postgres:
    secret:
      name: pg-admin-creds
      usernameKey: username
      passwordKey: password
    host: 127.0.0.1
  mariadb:
    secret:
      name: mariadb-admin-creds
      usernameKey: username
      passwordKey: password
    host: 127.0.0.1
  image: ghcr.io/notepass/external-db-user-provider